# baseURL = "https://emil-garnell.github.io/jeanlouisgarnell/"
baseURL = "https://emil-garnell.github.io/"
languageCode = 'en'
title = 'Jean-Louis Garnell'

defaultContentLanguage = 'en'

[module]
# uncomment line below for temporary local development of module
# or when using a 'theme' as a git submodule
replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
[[module.imports]]
path = "github.com/colinwilson/lotusdocs"
disable = false
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
disable = false

[params]
google_fonts = [["Roboto", "300, 400, 600, 700"], ["Fira Code", "500, 700"]]
sans_serif_font = "Roboto"
secondary_font = "Roboto"
# themeColor = "#6b6b6bff"

[params.docs]
# set the folder (section) the theme treats as the docs root
# change this to the section name you prefer, e.g. "" (root) or "docs"
themeColor = "gray"
title = ""
pathName = ""
toc = false

[params.flexsearch]
searchSectionsIndex = "ALL"

[params.landingpage]
enabled = false

[languages]
[languages.en]
disabled = false
languageCode = 'en'
languageDirection = ''
languageName = 'en'
title = 'Jean-Louis Garnell'
weight = 0
[languages.fr]
disabled = false
languageCode = 'fr'
languageDirection = ''
languageName = 'fr'
title = 'Jean-Louis Garnell'
weight = 1
